Update main_test.go
Update main_test.go

Update deploy.go

.

Update deploy.yml

fix

Delete go.mod

go.mod

Update deploy.yml

Revert "Update deploy.yml"

This reverts commit 3fced9e151c1836cce701855adafb3f705589593.

Update main_test.go

Update main_test.go

Update deploy.yml

Create main_test.go

Update main_test.go

Update deploy.yml

.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,10 +21,12 @@ jobs:
       run: go mod tidy  # Ensure dependencies are installed
     - name: Build
       run: go build -v ./...
-    - name: Run Go tests
-      # working-directory: function
-      run: go test -v ./cmd/gcptool
-
+    - name: function build
+      working-directory: function
+      run: go build -v ./...
+    - name: Run Go tests for function
+      working-directory: function
+      run: go test -v ./...
     - name: Authenticate to Google Cloud
       uses: google-github-actions/auth@v2
       with:
@@ -38,13 +40,21 @@ jobs:
 
     - name: Build gcptool
       run: go build -v -o gcptool ./cmd/gcptool
-      
+    - name: Confirm binary build
+      run: |
+        echo "Listing files in workspace:"
+        ls -lh
+        if [ -f ./gcptool ]; then
+          echo "gcptool binary exists and was built successfully."
+        else
+          echo "gcptool binary not found!"
+          exit 1
+        fi
+    - name: Run Go tests
+      run: go test -v ./cmd/gcptool
     - name: Describe deployed function
       run: ./gcptool describe carbonq
 
     - name: Deploy Function using gcptool
       if: success()
-      run: ./gcptool deploy carbonq -e dev -v v1.0.0 -c
-          --trigger-http \
-          --allow-unauthenticated \
-          --region us-central1
+      run: ./gcptool deploy carbonq --source=function -e dev -v v1.0.0 -c
