Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,10 +40,18 @@ jobs:
 
     - name: Build gcptool
       run: go build -v -o gcptool ./cmd/gcptool
+    - name: Confirm binary build
+      run: |
+        echo "Listing files in workspace:"
+        ls -lh
+        if [ -f ./gcptool ]; then
+          echo "gcptool binary exists and was built successfully."
+        else
+          echo "gcptool binary not found!"
+          exit 1
+        fi
     - name: Run Go tests
-      # working-directory: function
       run: go test -v ./cmd/gcptool
-
     - name: Describe deployed function
       run: ./gcptool describe carbonq
 
